### ISSUE TITLE
ngIdle doesn't work in a mobile application in background

### ISSUE THREAD

**Issue by hernangiraldo89** [HackedByChinese/ng-idle#100]
How are you friend?
I hope you are fine!

I'm develop an application with Worklight 6.2, AngularJS and Ionic v1.0.0-beta.1 and I have a problem using this module. When the application is in background, pass the time and never closes my session.

Some ideas?

thanks!

**Comment by HackedByChinese** [comment]
With version 1.1.0 this should be working (seems fine in rudimentary tests). There may have been other issues getting in the way that are being addressed in a release shortly. I'll close for housekeeping, you can reopen if you have further problems.
