### ISSUE TITLE
No ability to destroy Idle Object

### ISSUE THREAD

**Issue by jonathanwoahn** [HackedByChinese/ng-idle#101]
I only want to monitor Idle activity on part of my application (Using Angular/OnsenUI). Is there a way to destroy the Idle object when I navigate away from that part of the application?

**Comment by HackedByChinese** [comment]
It's a service, which are implemented as singletons in Angular, so there isn't a way to destroy the instance. However, you can cease the watch behavior by just calling `.unwatch()` when you navigate away, and `.watch()` when you navigate in (and want the behavior to resume again). 

How/where exactly to make those calls depends on what you're using for routing. If you're using normal Angular Routing module, you could use the [`$routeChangeSuccess`](https://docs.angularjs.org/api/ngRoute/service/$route#$routeChangeSuccess) event (the `current` and `previous` event parameters can be used to figure out when you're entering and when you're leaving the target route.

**Comment by jonathanwoahn** [comment]
Thanks! This is just what I needed.
