### ISSUE TITLE
Cyclical dependency using ngIdle with http interceptors

### ISSUE THREAD

**Issue by agentmerlin** [HackedByChinese/ng-idle#102]
This may just be more of a feature request, but I was attempting to use the the Idle service to strictly interrupt on http requests. Here is an example of the Interceptor service.

```javascript
angular.module('idleTest')
    .factory('IdleInterruptInterceptor', ['Idle', function (Idle) {

        // Manually interrupt the IdleService on every response
        return {
            response: function (response) {
                Idle.interrupt();
                return response;
            }
        };
    }]);
```

However, this is causing a circular dependency:

Uncaught Error: [$injector:cdep] Circular dependency found: $http <- Keepalive <- Idle <- IdleInterruptInterceptor <- $http

I'd love for the Idle service to be capable of being used with an interceptor, but I'm not sure the best way to go about adding that functionality in without dropping the dependency between Keepalive and $http or between Idle and Keepalive.

**Comment by HackedByChinese** [comment]
The only thing I can think of at the moment without radical changes is to have `Idle` monitor an event such as `Idle.interrupt` on rootScope, and when a message is received, it will just call `interrupt` on itself. It feels a little hackish, but it may work.

**Comment by toxaq** [comment]
ngidle could just use an $injector to load $http itself, rather than using DI. `$http = $injector.get('$http')`

**Comment by HackedByChinese** [comment]
That's true. He can also use `$injector` in his interceptor.

    .factory('IdleInterruptInterceptor', ['$injector', function($injector) {

       // Manually interrupt the IdleService on every response
       return {
         response: function(response) {
           $injector.get('Idle').interrupt();
           return response;
         }
       };
     }])

I've mentioned in other places that a future release should focus on modularizing the current functionality of ng-idle so people can pick and choose what they actually need, but this seems like a viable alternative for now.

http://plnkr.co/edit/HZW580Welvt2T4acT1yD?p=preview

**Comment by HackedByChinese** [comment]
I feel that adequate workarounds to make this work have been provided above.

**Comment by abilashs90** [comment]
Hi @HackedByChinese, I have a scenario where I have to renew my idle every single time a request is fired. I tried `interrupt` and `unwatch` and immediately `watch` again in the interceptor. Because I did something in the interceptor, `IdleTimeout` is not triggered. Because of this, a legitimate timeout is not timing out.

Any solutions?
