### ISSUE TITLE
Receiving an error after calling stop/unwatch and navigating to another page/view

### ISSUE THREAD

**Issue by fata13xception** [HackedByChinese/ng-idle#107]
I've attempted disabling the idle functionality when users navigate away from the current page/view using both the stop() function call and a direct Idle.unwatch() call, but I receive the following error after stop/unwatch is called and it transitions to any subsequent page/view. newValue is an empty String.

![02](https://cloud.githubusercontent.com/assets/13853158/9333337/677ebe88-4597-11e5-8780-a4adc65426ee.PNG)

I've tried placing the stop/unwatch in the controller's destroy and stateChangeStart... without any success.

![03](https://cloud.githubusercontent.com/assets/13853158/9333401/b509f28a-4597-11e5-9ece-32fb730ad1e3.PNG)

**Comment by HackedByChinese** [comment]
It is possible that this is related to #113 as suggested by @realbru. The fix for that will go out soon. I'm going to close this for now and you can reopen if it doesn't work out.
