### ISSUE TITLE
Closing warning model only on button click

### ISSUE THREAD

**Issue by DivakarPM** [HackedByChinese/ng-idle#109]
As of now we can able to close warning model for key down, mouse blink activities. Can we have button called Close in the model. On click of i need to close the model... Is this possible using ngIdle?

**Comment by HackedByChinese** [comment]
By default, ng-idle will interrupt the idle state if a user performs any DOM event specified in `IdleProvider.interrupt()`, so long as the user does not time out. I call this feature "auto resume". 

If you do not want auto resume, but would rather have more control over what the user needs to do to come back from being idle, you can set `IdleProvider.autoResume()` to `'notIdle'`. This means that interrupt events will keep the user active, but once they go idle, the only way to bring them back is for your application to call `Idle.watch()` (which you can do when your modal close button is called).

**Comment by kernwig** [comment]
I was looking for this feature. I had to find this (now) two-year old question to know what to do though. There's no mention of auto-resume in the documentation, and the comments in the code are unclear as to what auto-resume is. (The comments are useful once you know what the feature is, but not before.)

**Comment by grbsk** [comment]
The description has been in the wiki under autoResume since the feature was
released.
https://github.com/HackedByChinese/ng-idle/wiki/Idle-and-Idleprovider#idleprovider

**Comment by kernwig** [comment]
Thank you. So many github projects don't use their wiki, I didn't think to look.
