### ISSUE TITLE
Error: QuotaExceededError: DOM Exception 22 in Safari Private Browsing Mode

### ISSUE THREAD

**Issue by karthilxg** [HackedByChinese/ng-idle#111]
Getting the `DOM Exception: 22` while using the `ngIdle` in `Safari - private browsing mode`.

> Click the **Start Demo** button from the demo page http://hackedbychinese.github.io/ng-idle/

```js
Error: QuotaExceededError: DOM Exception 22
setItem@[native code]
set@https://rawgit.com/hackedbychinese/ng-idle/master/angular-idle.js:413:24
setExpiry@https://rawgit.com/hackedbychinese/ng-idle/master/angular-idle.js:207:32
watch@https://rawgit.com/hackedbychinese/ng-idle/master/angular-idle.js:245:43
start@http://hackedbychinese.github.io/ng-idle/js/app.js:42:15
https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:198:308
f@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:214:486
$eval@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:125:305
$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:126:11
https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:215:42
c@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:32:393
(anonymous function)angular.js:11443
(anonymous function)angular.js:8417
$applyangular.js:14356
```

**Comment by karthilxg** [comment]
Looks like Safari private browsing not supporting the `localStorage`, however it works in Chrome private browser mode.

> Apparently this is by design. When Safari (OS X or iOS) is in private browsing mode, it appears as though localStorage is available, but trying to call `setItem` throws an exception.

> store.js line 73
> "QUOTA_EXCEEDED_ERR: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota."
> What happens is that the window object still exposes localStorage in the global namespace, but when you call setItem, this exception is thrown. Any calls to removeItem are ignored.

http://stackoverflow.com/questions/14555347/html5-localstorage-error-with-safari-quota-exceeded-err-dom-exception-22-an

**Comment by jitendersandhu** [comment]
+1, I have the same problem

**Comment by jitendersandhu** [comment]
I tried this fall back fix (https://github.com/HackedByChinese/ng-idle/pull/112) and it works fine for me. Thanks @karthilxg!
@HackedByChinese - please take a look and see if you could merge this pull request. Thanks!

**Comment by geoffreytran** [comment]
+1 also running into the same issue here.

**Comment by HackedByChinese** [comment]
Resolved in develop
