### ISSUE TITLE
setIdle() - ngIdle.expiry event causes json.parse exception on internet explorer

### ISSUE THREAD

**Issue by realbru** [HackedByChinese/ng-idle#113]
When using IE with the IE debugger open (F12) an exception is thrown when Idle.setIdle() is called. I did not see this in Chrome.

It appears the 'newValue' in the 'wrap()' function is an empty string ("") and 'oldValue' is a valid time. Since they are different the code attempts to call 'fromJson' on an empty string which then throws in JSON.parse().

SCRIPT1002: Syntax error
File: angular.js, Line:1251, Column:3

I have uploaded a plunker project at the URL below that exhibits the problem in IE.

http://plnkr.co/edit/dKwjKAZnCwggMgSw5djx?p=preview

The project has 2 copies of the angular-idle.js file. The modified form has a check for newValue being empty.

You may need to press 'F5' after opening the debugger.

**Comment by realbru** [comment]
As an FYI this may be related to #107 as that appears to be the same area parsing a JSON string that may be an empty string.

**Comment by realbru** [comment]
I'm sure you are busy with other projects and stuff but wondering if you've taken a peek at this.

**Comment by HackedByChinese** [comment]
A project I've been working on most of the  year is rolling out to customers as we speak, and I just haven't had time to do much else than answer questions. I will work through these bugs once I get this monkey off my back.

**Comment by ETON-Pandiarajan-Rajendran** [comment]
Hi All, I'm using angular 1.3.7, I'm facing this error. Could you please let us know which version is this issue fixed?
