### ISSUE TITLE
Session Timeout Example

### ISSUE THREAD

**Issue by corydorning** [HackedByChinese/ng-idle#114]
I'm not 100% sure how keepAliveProvider works. What I'm looking to do is allow the user to be inactive for 28 minutes, before being prompted with a 2 minute timeout. The code I have to do this is this and it works fine:

```
myApp
  .controller('AppController', function($scope, $modal, Idle, Keepalive) {
    var vm = this;

    vm.closeSessionTimeout = function() {
      // modal exists?
      if(vm.sessionTimeoutModal) {
        // close modal
        vm.sessionTimeoutModal.close();
      }
    };

    $scope.$on('IdleStart', function() {
      // close modal
      vm.closeSessionTimeout();

      // create modal
      vm.sessionTimeoutModal = $modal.open({
        templateUrl: 'session-timeout.html'
      });
    });

    $scope.$on('IdleEnd', function() {
      // close modal
      vm.closeSessionTimeout();
    });
  })

  .config(function(IdleProvider, KeepaliveProvider) {
    // idle time allowed (28 minutes)
    IdleProvider.idle(1680);

    // Countdown before timeout (2 minutes)
    IdleProvider.timeout(120);
  })

  .run(['Idle', function(Idle) {
    // starts the Idle state when app is loaded
    Idle.watch();
  }])
;
```

However, how do I incorporate the keepAliveProvider to make a call to a given url (`/keepalive.gif`) to make sure my session on the server remains in tact?

**Comment by HackedByChinese** [comment]
keepalive is used to ping a URL at a regular interval in cases where your server side needs feedback regular from the client to keep a session alive. The frequency and the URL are configurable. If you don't provide a URL, it'll issue an event that you can respond to in your application to do the keepalive work (this is useful for cases where a simple hit to a URL won't sufficiently keep your session alive). By default, it's every 10 minutes, but it has no URL configured. 

Idle uses keepalive to actively ping the server at said interval while the user is not idle or timed out. When a user becomes idle or times out, it stops the keepalive from occurring (although you can still force it to ping manually). It will resume pinging once the user is no longer idle or timed out. Furthermore, idle will cause an immediate keepalive ping when a user goes from idle to not idle, and then resume the regular keepalive interval. This behavior is turned on by default, but can be turned off. 

See the wiki for keepalive and idle for more information.

**Comment by corydorning** [comment]
Yeah i read through the wiki but I wasn't exactly sure how to implement it. Would I add the keepalive url to my config block like this?

```
.config(function(IdleProvider, KeepaliveProvider) {
  // idle time allowed (28 minutes)
  IdleProvider.idle(1680);

  // Countdown before timeout (2 minutes)
  IdleProvider.timeout(120);

  // renew session with the server
  KeepaliveProvider.http('/keepalive')
})
```

The part that is confusing is this *"It will resume pinging once the user is no longer idle or timed out. Furthermore, idle will cause an immediate keepalive ping when a user goes from idle to not idle, and then resume the regular keepalive interval."*

If the user is idle for 30 seconds, and then starts moving the mouse, is idle going to trigger the keepalive ping? This seems like a like of calls to the server. Just want to make sure I"m understanding this correctly.

**Comment by corydorning** [comment]
I guess what I'm wondering is, how long does the user have to be 'idle' before they are considered idle.

**Comment by corydorning** [comment]
Okay...so i think i may get it now. Sorry for being dense and correct me if I'm wrong. Here it goes:

The `KeepaliveProvider.http` call will be made every 10 minutes (default), unless the user becomes idle,  which in my case is 28 minutes. At that point a 2 minute timeout will be set. Once the timeout countdown begins no http calls are made unless the user becomes active again, at which point the http request is made and the 10 minute call to the server is reset.

**Comment by HackedByChinese** [comment]
That's correct.

**Comment by Pranavkakkar** [comment]
I Just implemented the ngidle in my angularjs project.
the issue i'm facing is that it only shows the time counter on the top of the chrome menu. 
And I'm not getting how to logout the active user when the session expires.

**Comment by JayTanna1** [comment]
I am unable to modify the interval of KeepaliveProvider. I want to send a backend call to renew session every 5mins. I have written  KeepaliveProvider.interval(300) in the config; but it makes a call only every 10mins even though I have set it for 5mins.
