### ISSUE TITLE
idletimeout in run function

### ISSUE THREAD

**Issue by joshikeerti** [HackedByChinese/ng-idle#115]
If I have multiple routes, each using a different controller, would I just handle the Idletimeouts in the .run function? I don't want to have the same code in all my controllers.

**Comment by HackedByChinese** [comment]
The intended application of ng-idle is to set it up once in your application's .run and be done with it. It does not need to be set up for each controller or route. It does not support different settings for different routes; you'll have to hack that yourself if you need that.
