### ISSUE TITLE
Error when having two open tabs

### ISSUE THREAD

**Issue by pdamicol** [HackedByChinese/ng-idle#116]
I'm experiencing an issue similar to #72 whenever I have two tabs open of my angular application I get errors in the console roughly every second. I do expect the behaviour that if a user is working on a tab, he/she won't be logged out on the other. However, all I keep getting is this error.

The error reads Uncaught TypeError: Cannot read property 'id' of null (angular-idle.js:285)

I'm using ng-idle v 1.1.0 and angular v 1.4.5

Thanks.

**Comment by jitendersandhu** [comment]
+1 facing same issue as this one. posted a screenshot below for reference.

>wrapangular-idle.js:285 TypeError: null is not an object (evaluating 'val.id')
wrapangular-idle.js:284


![image](https://cloud.githubusercontent.com/assets/14833247/10237301/caa887ba-6864-11e5-8d75-61f5515a16ca.png)

**Comment by HackedByChinese** [comment]
This is likely related to #113, which is fixed and will be released shortly. Reopen if it doesn't address the issue.
