### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating '$window.attachEvent('onstorage', wrap)')

### ISSUE THREAD

**Issue by optimacycorp** [HackedByChinese/ng-idle#117]
Getting the following error using Karma and a spec helper with $provide to allow access to $window.  However, it doesn't like this when run through PhantomJS 2.0.   Unfortunately, I can't provide source code as it is proprietary app. I am trying to make a test case with just the failing software.  Any ideas would be helpful, thanks.

**Comment by kevinverelst** [comment]
Any luck on fixing this? I'm bumping into the same issue

**Comment by andreibondarev** [comment]
Same here. I've just encountered the same exact issue.

**Comment by kevinverelst** [comment]
I temporarily 'fixed' it by stubbing the attachEvent function on the window

**Comment by kevinverelst** [comment]
That check should do the trick
