### ISSUE TITLE
$scope.$on('IdleTimeout' callback only gets called once

### ISSUE THREAD

**Issue by bmwertman** [HackedByChinese/ng-idle#122]
I'm using this to have the user sign in again if they have been idle too long. I call `Idle.watch() in the run method of my app.js. I set the idle time short(3 sec.) in the config. If I interact with the app after 3 seconds my login modal shows. After I login and wait 3 seconds more the modal does not show.

I would like, obviously, for the modal to continually show each time the idle time limit has been reached. The other thing I would like is if the user did not have to interact with the app to get the login modal to show. Instead just have it popup when the idle time limit has been reached. 

Here is my app.js

```
.run(function ($ionicPlatform, $sailsSocket, $rootScope, $localstorage, Idle) {
  $ionicPlatform.ready(function () {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if (window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
    if (window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleDefault();
    }
  });

  //Start watching for user inactivity
  Idle.watch();
  $ionicPlatform.onHardwareBackButton( function(){
     Idle.interrupt();
  });

.config([
  '$stateProvider', 
  '$urlRouterProvider', 
  '$validationProvider', 
  '$ionicConfigProvider', 
  '$sailsSocketProvider', 
  'jwtInterceptorProvider',
  'IdleProvider',
  function ($stateProvider, $urlRouterProvider, $validationProvider, $ionicConfigProvider, $sailsSocketProvider, jwtInterceptorProvider, IdleProvider) {

    //Sets the inactive time in seconds before user is signed out
    IdleProvider.idle(3);
    IdleProvider.timeout(false);
    IdleProvider.keepalive(false);
.
.
.
])
```
and my signin controller
```
app.controller('SigninCtrl', [
  '$scope',
  '$ionicModal',
  '$sailsSocket', 
  '$localstorage', 
  '$ionicLoading', 
  '$location', 
  'Idle', 
  function ($scope, $ionicModal, $sailsSocket, $localstorage, $ionicLoading, $location, Idle) {
  // Create the login modal that we will use later
  $ionicModal.fromTemplateUrl('signin/templates/signin.html', {
    scope: $scope
  }).then(function (modal) {
    $scope.modal = modal;
  });

  // Triggered in the login modal to close it
  $scope.closeSignin = function () {
    $scope.modal.hide();
    console.log('hello');
  };

  $scope.$on('$destroy', function () {
    $scope.modal.remove();
  });

  // Open the login modal
  $scope.signin = function () {
    $scope.modal.show();
  };

  //signout the user if they have been idel too long
  $scope.$on('IdleTimeout', function() {
    $scope.signin();
  });

  // Perform the login action when the user submits the login form
  $scope.doSignin = function () {
    // Idle.watch();//resume idle watch started in the run block
    $sailsSocket({
      method: 'GET',
      url: '/servicemanager/signin',
      headers: $scope.signin
    })
    .then( function (res) {
      $localstorage.set('authToken', res.data.Authorization);
      $ionicLoading.show({
        template: res.data.message,
        duration: 3000
      });
      $scope.modal.hide();
      $location.path('/');
    })
    .catch( function (err){
      console.log(err);
    });
  };
}]);
```

**Comment by HackedByChinese** [comment]
Hmm,  you have `IdleProvider.timeout(false)` in your config, which should disable the timeout feature, and thus `IdleTimeout` shouldn't be getting called at all (if it does, it wasn't intended). When you use `timeout(false)`, it sets `Idle` into a mode where all it does is try to detect when a user goes inactive and becomes active again via the `IdleStart` and `IdleEnd` events ([see wiki](https://github.com/HackedByChinese/ng-idle/wiki/Idle-and-Idleprovider#idleprovider)).

Furthermore, be aware that if `SigninCtrl` goes out of scope, none of your behavior will work. To be more explicit, if `SigninCtrl` is (for example) used on a header of every page, it'll probably be OK. But if the controller is only used on a specific view, if that view goes out of scope, none of your functionality will work.

**Comment by bmwertman** [comment]
If I'm calling `Idle.watch` in the `.run()` do I need to call it again each time the idle time limit is reached?

**Comment by HackedByChinese** [comment]
If the `IdleTimeout` event is raised (again, it shouldn't be getting raised when you disable the timeout feature as I mentioned earlier), then yes, you will need to call `.watch()` to continue. When a user is considered timed out, Idle is designed not to resume their session unless the application specifically tells them to.

**Comment by HackedByChinese** [comment]
I'm closing this for housekeeping. If you feel there is still an issue, please reopen with more details.

**Comment by catiamatos1991** [comment]
I'm having troubles to put a unwatch on a controller. I have a layoutController which is common to some controllers that i used but for one I want to disable ng-idle and my code  is:

(function () {
    var app = angular.module('map.controller',['ui.bootstrap', 'ngIdle']);

    app.controller('MapController',['$rootScope', '$scope', '$sce', '$http','Idle', 'Keepalive', '$uibModal', function ($rootScope, $scope, $sce, $http, Idle, Keepalive, $uibModal) {
        var controllerScope = $scope;
      	controllerScope.iframeUrl = $sce.trustAsResourceUrl('https://wavesys-dot-gliiide2.appspot.com/nauta?organization_id=' + $rootScope.organization.id);
    	
        
        app.config(['IdleProvider', function(IdleProvider) {
            IdleProvider.keepalive(false);
            IdleProvider.timeout(false);

        }]);

        app.run(['Idle', function(Idle) {
            Idle.unwatch();
        }]);
                
    }]);
})();
