### ISSUE TITLE
Help! LocalStorage disabled on target system

### ISSUE THREAD

**Issue by sjl2024** [HackedByChinese/ng-idle#123]
Is there any way to make this plugin work without relying on localStorage?

**Comment by HackedByChinese** [comment]
Unfortunately not. This feature has been a huge headache and I'm thinking of making it an add-on rather than a permanent component. But that doesn't help you right now. Unfortunately, you'll have to monkeypatch or fork your own to remove it.

**Comment by HackedByChinese** [comment]
I misspoke (slightly). When #112 is released, there will be a fallback if localStorage is not accessible. However a) the multitab coordination will not work (meaning that activity in one window to the same application will not affect another) b) you currently cannot configure this feature to be disabled from the get-go. I'll add the ability to control this later.
