### ISSUE TITLE
ngIdle.expiry exception, after 'unwatch' is invoked

### ISSUE THREAD

**Issue by SeanSobey** [HackedByChinese/ng-idle#125]
In my implementation of this, after following the suggested examples, it all works ok, but I am seeing a javascript error:
Line 298 of angular-idle.js

var wrap = function(event) {
          if (event.key === 'ngIdle.expiry' && event.newValue !== event.oldValue) {
            var val = angular.fromJson(event.newValue);
            if (val.id === id) return;
            svc.interrupt(true);
          }
        };

event.newValue is an empty string, so angular.fromJson() complains

**Comment by HackedByChinese** [comment]
This is addressed in #113

**Comment by SeanSobey** [comment]
The latest files in this github repository do not seem to have that change included. Is there another place I am supposed to get them?

**Comment by HackedByChinese** [comment]
It does contain this change: https://github.com/HackedByChinese/ng-idle/commit/2b72e7811b1b0e8b87f63e5fc93e58e2a64e8395
