### ISSUE TITLE
Not working on iOS Safari

### ISSUE THREAD

**Issue by aaronbc** [HackedByChinese/ng-idle#126]
When I enable ng-idle on my page and access it from Safari angular is broken.  Comment out Idle.watch() and the page works fine.  I also can't run the demo on this site from an iPad.

**Comment by HackedByChinese** [comment]
Please provide more information.

1. What model device and iOS version are you using?
2. Can you provide a demo site or plunkr (or similar) that replicates the issue?
3. Are there any errors logged in the debug console (you'll need to either enable this feature in Settings for Safari, or try debugging during iOS emulation in Safari)?
4. What are you expecting it to do vs what it is actually doing?
5. What version of Angular and ng-idle are you using?

There are a number of open issues resulting from multi-tab support that I need to resolve. However, I ran the demo on my phone and my iPad (a 5s and original Mini, both using latest iOS) as well as emulated the most recent devices and I had no problems with the demo.

**Comment by ruimserrano** [comment]
+1
Sometimes works, in private browsing never works
i got this error
QUOTA_EXCEEDED_ERR: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.

**Comment by HackedByChinese** [comment]
@ruimserrano The private browsing issue was addressed in 1.1.1 which went out last night.

**Comment by ruimserrano** [comment]
great..i've updated the lib and it's working now.
Thanks

Keep up the good work

**Comment by aaronbc** [comment]
Yes, this turned out to be a private browsing issue.  Thanks for the fix.
