### ISSUE TITLE
Localization of page title text

### ISSUE THREAD

**Issue by patrickrioux** [HackedByChinese/ng-idle#128]
Really like the page title functionality but I don't see any option to set the page title manually as per language. This is hardcoded in the source.  Can this be supported soon from the TitleProvider?

 var state = {
        original: null,
        idle: '{{minutes}}:{{seconds}} until your session times out!',
        timedout: 'Your session has expired.'
      };

**Comment by HackedByChinese** [comment]
Currently it's only configurable via `Title`. https://github.com/HackedByChinese/ng-idle/wiki/Title

**Comment by patrickrioux** [comment]
Can you point me an example?  I want to change the browser tab title text. 
Instead of '{{minutes}}:{{seconds}} until your session times out!
I want to localize this string in different language. By reading the documentation, I have no clue on how to achieve this via Title.

**Comment by HackedByChinese** [comment]
in your module's `.run()`, inject `Title` and use the appropriate method to change the value you want.

    angular.module('myapp', ['ngIdle'])
      // ...
      .run(function(Title) {
         Title.idleMessage('You are idle');
      });

I realize it would be more intuitive if these values could be set via `TitleProvider`, but the effect is the same. I'll add that in a later release.

**Comment by patrickrioux** [comment]
Thank you. Work great!
