### ISSUE TITLE
Calling Idle.watch() in 'IdleStart' callback does not reset 'IdleTimeout' timer

### ISSUE THREAD

**Issue by jtallen** [HackedByChinese/ng-idle#131]
Hey there! So far ngIdle has been massively helpful to me, but I am now unfortunately running into a problem that I am unable to get around on my own. I have scoured the wiki trying to figure out where I am going wrong, but haven't had any luck.

I am trying to set an idle timer that checks a condition when 'IdleStart' is broadcast, and then resets the idle timer if the condition is true. Unfortunately, the timer doesn't seem to be resetting when I call 'Idle.watch()' or 'Idle.interrupt()'. I'm not sure why this is behaving this way, perhaps you cannot call Idle.watch() from your 'IdleStart' callback? Below is a pared down version of my code, I have taken out all extraneous information, and this is more of an example of what is going wrong, thanks in advance for any support you can give me on this, even if it is just linking me to something in the wiki that I missed! ;)

```javascript
angular
  .module('app')
  .config(configBlock)
  .run(runBlock);

function configBlock(IdleProvider) {
  IdleProvider.idle(5);
  IdleProvider.timeout(10); // low values for testing
}

function runBlock($rootScope, Idle, myFactory) {
  Idle.watch();
  $rootScope.$on('IdleStart', idleCallback);
  $rootScope.$on('IdleTimeout', timeoutCallback);

  function idleCallback() {
    if (myFactory.checkMyCondition()) {
      Idle.watch(); // should reset idleTimer, but doesn't
    } else {
      // warn user of imminent logout
    }
  }

  function timeoutCallback() {
    // log user out
  }
}
```

In practice, this is how the above code executes: Page is loaded, 5 seconds of idle time and the idleCallback is called, `myFactory.checkMyCondition()` evaluates to true, so Idle.watch() is called. This is where you would expect the Idle Timer to be reset, however, no idle warning is displayed 5 seconds later as it should, and 10 seconds later, the timeoutCallback is called. If you have any idea what could be causing this, please let me know - thanks!

Edit: As mentioned earlier, the code above is much-pared down, you may assume for the purpose of viewing this that everything works and is wired up correctly (including the initial app.module with dependencies).

**Comment by wmfairuz** [comment]
Any fix / wordaround on this issue? Thanks

**Comment by hongsheng-razoo** [comment]
I ran into this problem too and wrapping the Idle.watch() in $timeout() solved this problem:  $timeout(function () {
          Idle.watch();
        });
