### ISSUE TITLE
make idle should only work for server request

### ISSUE THREAD

**Issue by Jeevanandanj** [HackedByChinese/ng-idle#132]
I've my own api and I've set api time out. So when the user interaction is idle for sometime (in server perspective), then system token will expire, even if the angular idle is live because of mouse interaction.

How to set idle should alive only for the user interaction with the server. Not for the UI perspective.

**Comment by HackedByChinese** [comment]
The model this module is designed to follow is where a keepalive ping can be sent to the server periodically to keep the token alive on the server side. This is all managed by the `Keepalive` service. You'll need to configure it with a URL + any HTTP options that I will send to the server when it pings ([see the wiki for more information](https://github.com/HackedByChinese/ng-idle/wiki/Keepalive-and-Keepaliveprovider)). If the built-in mechanism for sending an HTTP request to ping is insufficient, you can listen in on the `Keepalive` event which is broadcast from the root scope and do whatever you need to do to update your server.

The Keepalive is designed to keep pinging at an interval you specify (10 minutes by default) _while the user is not idle_. When the user goes idle, the pinging is paused, and will resume when they stop being idle. If the user does not resume activity in time, they time out, and keepalive will not continue pinging.

**Comment by Jeevanandanj** [comment]
This has been already addressed in the following link. So I am closing this. https://github.com/HackedByChinese/ng-idle/issues/51
