### ISSUE TITLE
Calling Idle.watch() breaks my other $scope.$watch functions

### ISSUE THREAD

**Issue by hayatnoor** [HackedByChinese/ng-idle#134]
I just started using this library and noticed that my other $scope.$watch functions are dead when I call Idle.watch(). They are multiple-select fields and when I select anything, those $watch functions pick up nothing. When I comment out Idle.watch(), all works well. Any ideas?

**Comment by hayatnoor** [comment]
Perhaps my Angular version is not a compatible version with this library? Which version of Angular has this been tested on?

**Comment by HackedByChinese** [comment]
#103 reported a similar issue that I haven't resolved (this user provided an actual example). It may be a bug in the `select` directive. I have noticed that upgrading to at least Angular 1.3 fixes that particular example.

Let's try this the other way around, why don't you tell me what version you're using?

**Comment by hayatnoor** [comment]
I'm using v1.2.9... I will try upgrading to 1.3 and see if that resolves the problem (and hopefully doesn't break other stuff :smiley: )

**Comment by hayatnoor** [comment]
So it looks like Angular 1.3.0 breaks some other stuff with my app as they made some major changes in that from 1.2.9. Perhaps it would be a good idea to mention in the README that this plugin requires at least Angular 1.3.0.

**Comment by HackedByChinese** [comment]
Well, this is a very specific issue. I don't think that a single bug in Angular (if it is indeed Angular) is a reason to call the whole thing off, as many people are using it with 1.2. I haven't concluded the investigation yet so let's hang on. Worst case scenario is a specific workaround to not monitor interrupt events on multi selects.

**Comment by hayatnoor** [comment]
You're right... it is a very specific scenario. It seems to only be related to multi-select inputs. If you happen to come across a fix for this, let me know. I don't really expect you to support a legacy version of angular.

**Comment by HackedByChinese** [comment]
If you are desperate need of an immediate workaround, you can try removing "click" as one of the interrupt events. Unfortunately, that means no clicking anywhere will interrupt. But the mouse movement and scrolling will probably catch most user activity.

**Comment by hayatnoor** [comment]
That worked! I removed 'mousedown' from the interrupt events and all is well. Thanks!

**Comment by HackedByChinese** [comment]
I'll close this. For permanent solutions to this sort of bug, if we find one, watch #103.
