### ISSUE TITLE
Keep alive warning message

### ISSUE THREAD

**Issue by Jeevanandanj** [HackedByChinese/ng-idle#135]
Can we have keep alive warning message?

**Comment by HackedByChinese** [comment]
I don't understand the request. Can you provide a clearer use case?

**Comment by Jeevanandanj** [comment]
when user in page idle, then there will be a warning message that user is going to be logged out because of session expired.
Like that can we have if we implement keep alive functionality.

**Comment by HackedByChinese** [comment]
You want to notify a user whenever a keepalive ping happens? I'm not sure why you'd want to do that, but if that's the case, you can listen for the Keepalive event in a controller or on the rootScope.

     $scope.$on('Keepalive', function() {
       // do something on keepalive; show modal, etc.
     });
