### ISSUE TITLE
UI Bootstrap 1.0.0+

### ISSUE THREAD

**Issue by solarisfire** [HackedByChinese/ng-idle#136]
Can the demo's and documentation be upgraded to work with UI Bootstrap 1.0.0+?

A lot of the directives have now been changed.

**Comment by getsetbro** [comment]
Agreed. Until then using $uibModal instead of $modal was the only difference for me.

**Comment by anuja-joshi** [comment]
@HackedByChinese  I would like to send PR with latest UI Bootstrap( 2.1.3), which also needs AngularJS upgrade to 1.4.x or higher.

**Comment by HackedByChinese** [comment]
@anuja-joshi Sounds good, if you'd like to.
