### ISSUE TITLE
Timeout if client goes to sleep

### ISSUE THREAD

**Issue by bwolohan** [HackedByChinese/ng-idle#138]
If the client PC, tablet, whatever goes to sleep the idle timer goes to sleep too. When it wakes back up it seems that the application detects that as activity so the timeout doesn't happen, even if it was asleep longer than the timeout period. I need to set my app up so that it always goes to the login screen when the timeout expires. if the device goes to sleep after say 5 minutes the timer still tracks from the last activity. If the timeout is set to 30 minutes and they come back after 10 they will continue where they left off. However if they come back after an hour they should immediately be redirected to the login screen. Is this possible?

**Comment by HackedByChinese** [comment]
What version of ng-idle are you using? It should be doing that since v1. It stores a timestamp of the last activity, and upon interrupting, it checks to see if the idle interval was exceeded, and should time you out.

**Comment by bwolohan** [comment]
Thanks for the quick response. I am using the latest version. I put together a small test app and it seems to work OK when my tablet to goes to sleep. I'm looking into my app to see why it's not doing what I expect. I'll let you know if I need more help,
