### ISSUE TITLE
Angular and title changes

### ISSUE THREAD

**Issue by bgold0** [HackedByChinese/ng-idle#139]
First off, thank you so much for making this; this works perfectly for my needs and you saved me a helluva lot of time.

I'm using Angular and I only use the ng-idle in one specific page. So if a user goes idle and the "session has expired" so to speak, that `<title>` will go throughout each page. Is there a easy way to refresh the title?

**Comment by HackedByChinese** [comment]
Thanks for the feedback. 

There is a service for Title that you could use to restore or manually set the title when you navigate outside the page. You can also disable the directive entirely and manage the title yourself, if the current implementation is too finicky. 

https://github.com/HackedByChinese/ng-idle/wiki/Title

**Comment by bgold0** [comment]
Ah perfect! Thank you.
