### ISSUE TITLE
localStorage access denied by browser

### ISSUE THREAD

**Issue by d-nation** [HackedByChinese/ng-idle#141]
Is there a strategy for dealing with browsers who have settings set to not allow website data? I have a lot of users who are on tightly controlled machines and some have this setting.

Unfortunately, this denies access to window.localStorage, causing a blocking error just loading ng-idle.

I can swallow that error by wrapping ngIdle.localStorage calls in try-catch blocks, but that means that it ngIdle actually isn't working and has then silently failed.  

I'd submit a PR with this fix, but I'm worried that for other users, failing silently might be just as bad as failing catastrophically  :smiley:

**Comment by HackedByChinese** [comment]
It does have a backup (https://github.com/HackedByChinese/ng-idle/blob/develop/src/localStorage/localStorage.js#L10) in case there are accessor issues. However, if I missed a spot where an exception is thrown, let me know, or yeah, a PR will work.

The strategy currently is that if local storage isn't available, it just falls back to in memory. The side effect, though, is that you won't be able to coordinate amongst tabs.

**Comment by d-nation** [comment]
Well, poop. I was looking at my local copy that I was using until my previous PR gets published to bower. It looks like the version you linked to is doing pretty much exactly what I did to the older version. Sorry for the trouble, and thanks again for maintaining this!

**Comment by HackedByChinese** [comment]
I'll release pulled but unreleased stuff by the end of the work week. Sorry about that.

**Comment by d-nation** [comment]
No need to be sorry :smile: I wasn't trying to make you feel guilty or anything. Was just trying to explain why I looked like the chap who didn't read the docs :neutral_face: Again, I appreciate even having your library available, thanks!
