### ISSUE TITLE
Multiple instances of IdleProvider and KeepaliveProvider to idle and timeout on different times

### ISSUE THREAD

**Issue by dadoadk** [HackedByChinese/ng-idle#142]
Hi, I'm looking if there's a way I can have two Idle timers to run in my application. One timer would run the Idle.watch() on app.run, and another timer would run Idle.watch() only on one page where timeout needs to be shorter and invoke different modal than the first timer. 
I'd appreciate any answer. Thanks.

**Comment by HackedByChinese** [comment]
Services in Angular are singletons, and indeed `Idle` both requires and is constrained by this fact. So you can't have separate instances. However, it seems reasonable that when you navigate to the route where you need to shorten the timer or change the modal, you could just inject `Idle` into the controller (or route resolver) and change the timeout or idle value to what you need (see `Idle.setTimeout()` and `Idle.setIdle()`), then change it back when you navigate away.

For the actual dialog, well... subscribing to the idle/timeout/warning events in the controller is easy enough, you just need a way to disable your default modal handling while you need the custom modal showing. You could wrap your whole handling into a single service that takes in `Idle` and `$rootScope`, wires up all the modal handling you need, but has a method or prop your route or controller can take in swap the modals. This is off the top of my head, meant to illustrate so sorry about errors.


```
.service('IdleManager', function($rootScope, $uibModal, Idle) {
  var options = {
     timeout: 10*60,
     warning: 30,
     modalIdleProps: {
      title: '...',
      message: '...'
    },
    modalTimedoutProps: {
      title: '...',
      message: '...'
    }
  }; 

 $rootScope.$on('IdleStart', function() {
   // show modal
  });

 $rootScope.$on('IdleEnd', function() {
   // hide modal
 });

 $rootScope.$on('IdleWarn', function() {
   // update countdown on modal
 });

 $rootScope.$on('IdleTimeout', function() {
   // show timeout modal
 });

  return {
     options: function(value) {
          if (value) {
             options = value;
             Idle.setTimeout(options.timeout);
             Idle.setIdle(options.idle);
             Idle.watch();
          }
          return options;
     }
  }
});
```

Now in your app's `run()` you can inject `IdleManager` and call `IdleManager.options()` with your default options. Whenever you need it to change, like during a route change or inside a controller, you just inject `IdleManager` and set options again, and reset it when you leave that route or controller.
