### ISSUE TITLE
Max session time

### ISSUE THREAD

**Issue by anterokarttunen** [HackedByChinese/ng-idle#143]
Hey,

I was wondering that it would be nice to have max session time - after that user would be logged out even if active.

Example: 
- max session time 1hour
- timeout 15min

Normal user interactions would reset timeout  - however when 1 hour has passed - it would logout user (call some $.on('max-session-timeout', ...) for example)

**Comment by anuja-joshi** [comment]
@anterokarttunen I do not think this functionality should be provided by **ng-idle** ,  the whole purpose of **ng-idle** is to watch for idle users and take actions accordingly.
If you want user to logout after certain interval, irrespective of inactivity/activity you should set expiry for your `cookies`.
Like, here you want to end session after 1 hour then:
```
  $cookies.putObject('loggedInUser', userObject, {expires:  60 * 60 * 1000 })
```
and use `ngIdle` for timout of 15min.

**Comment by anterokarttunen** [comment]
Ah, thanks for the tip :)



Lähetetty Samsung-laitteesta


-------- Alkuperäinen viesti --------
Lähettäjä: Anuja Joshi <notifications@github.com>
Päivämäärä: 28.8.2016 18.43 (GMT+02:00)
Saaja: HackedByChinese/ng-idle <ng-idle@noreply.github.com>
Kopio: Antero Karttunen <antero.karttunen@jaspartners.com>, Mention <mention@noreply.github.com>
Aihe: Re: [HackedByChinese/ng-idle] Max session time (#143)


@anterokarttunen<https://github.com/anterokarttunen> I do not think this functionality should be provided by ng-idle , the whole purpose of ng-idle is to watch for idle users and take actions accordingly.
If you want user to logout after certain interval, irrespective of inactivity/activity you should set expiry for your cookies.
Like, here you want to end session after 1 hour then:

  $cookies.putObject('loggedInUser', userObject, {expires:  60 * 60 * 1000 })


and use ngIdle for timout of 15min.

-
