### ISSUE TITLE
ng-idle has main set to a non-existent index.js file

### ISSUE THREAD

**Issue by arbylee** [HackedByChinese/ng-idle#150]
package.json has the "main" file set as index.js which does not exist.  This is causing problems when trying to include this library.  It looks like the index.js was accidentally removed during the last version bump.  I've submitted https://github.com/HackedByChinese/ng-idle/pull/149 to resolve the issue

**Comment by KristjanTammekivi** [comment]
Yup, removed in 6d440e8c0e5ae168acde9497075c5762ee05565b for some reason

**Comment by ChrisPiechowicz** [comment]
+1
