### ISSUE TITLE
TitleProvider.enabled is not a function

### ISSUE THREAD

**Issue by anilkumarpotluri** [HackedByChinese/ng-idle#152]
Hi,

https://github.com/HackedByChinese/ng-idle/wiki/Title saying that we can disable Title Provider by using  TitleProvider.enabled(false) in v1.0.0 or higher

When I use TitleProvider.enabled with version v1.1.0 throwing  the below error
TitleProvider.enabled is not a function

When I use the same  with version v1.2.0 it's working fine.

Some on please guide  us 
1. On which version it was added 
2. What all are the compatible version to use TitleProvider and  TitleProvider.enabled

Thanks,
Anil.

**Comment by HackedByChinese** [comment]
It was added in [1.1.1](https://github.com/HackedByChinese/ng-idle/releases/tag/1.1.1)
