### ISSUE TITLE
Interrupt callback

### ISSUE THREAD

**Issue by gindulis** [HackedByChinese/ng-idle#153]
Is there an event or callback for interrupt, I would like to do something when user interrupts.

My config:
`IdleProvider.interrupt('keydown mousedown touchstart')`

Is it possible to do using ng-idle or I have to manually bind to those events, would that be reliable?
`$('html').on('keydown mousedown touchstart', function(e) {
   // do something
});`

**Comment by HackedByChinese** [comment]
There was a pull request to broadcast an event upon interrupt. I'll have to see where that went.

**Comment by anuja-joshi** [comment]
@HackedByChinese I think, here you are referring to this pull request - [add broadcast for user activity #99](https://github.com/HackedByChinese/ng-idle/pull/99)
