### ISSUE TITLE
No setInterrupt for Idle service?

### ISSUE THREAD

**Issue by needforspeed** [HackedByChinese/ng-idle#155]
I'm trying to follow example in https://github.com/HackedByChinese/ng-idle/issues/142, but I need to select only a few events to interrupt the idleness. How can I do it?

Thank you!

**Comment by HackedByChinese** [comment]
See the [entry](https://github.com/HackedByChinese/ng-idle/wiki/Idle-and-Idleprovider#idleprovider) for `IdleProvider.interrupt()` to see how to change what events it should interrupt on.
