### ISSUE TITLE
Idle not working in multiple tabs.

### ISSUE THREAD

**Issue by skbelalmd** [HackedByChinese/ng-idle#156]
I have configured the idle service as
app.config(['KeepaliveProvider', 'IdleProvider', function(KeepaliveProvider, IdleProvider)  {
  IdleProvider.idle(5);
  IdleProvider.timeout(600);
 KeepaliveProvider.interval(10);
 }])

My webpage have some links targeted to new tab (under same domain).
While working in the main page(home page), the idle service runs as expected, but if i navigate to other tab by the link and work on that tab, after 6 minutes, the instance on 1st tab calls idle timeout.

It means that the idle service in both the tabs is not synchronous.

I want that the idle service should consider all the instances of an application as one, and the timeout would be called considering the idleness of all tabs.

**Comment by HackedByChinese** [comment]
It should work as you describe. You'll need to provide some details (browser and version, any errors in the console, etc.) or a sample app to do anything else.

**Comment by rajarajac** [comment]
Hi Shaikh Belall,

Did your scenario worked atlast?

Thanks,
Raj

**Comment by belall-shaikh** [comment]
Yes, 
I had to update to the latest version.
