### ISSUE TITLE
Idle Warn not working properly for inactive tabs

### ISSUE THREAD

**Issue by akshitsawhneyseedoc** [HackedByChinese/ng-idle#157]
Hi....
I am using ng-idle with the following configurations in my project:
```
module.config(['KeepaliveProvider', 'IdleProvider', function(KeepaliveProvider, IdleProvider) {
        IdleProvider.idle(30);
        IdleProvider.timeout(120);
        KeepaliveProvider.interval(120);
    }]);
```

This works fine, and I recieve Idle warn event every second if that tab is active.
But, the problem occurs when the tab is inactive. I receive the Idle warn event after some delays.
```
$scope.$on('IdleWarn', function(e, countdown) {
            console.log(new Date().getTime());    
        });
```
Any solution for this problem???
The following are my browser/machine details:
UserAgent: "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
Platform: "Win32"

**Comment by HackedByChinese** [comment]
Many browsers throttle background scripts executing on inactive tabs so they don't drain power, etc. So you'll often see them not execute in a timely fashion.

See my response [here](https://github.com/HackedByChinese/ng-idle/issues/158#issuecomment-227622242) to a similar inquiry for more info.
