### ISSUE TITLE
debugging question

### ISSUE THREAD

**Issue by ScottCumming** [HackedByChinese/ng-idle#159]
I have configured Idle with a timeout of 10 minutes. and I start watching for idleness. Is there any way to:
a) observe the timeout during the watch?; and..
b) ascertain what (if any) watched event has been triggered and has thus caused the timeout to be reset?

many thanks

**Comment by HackedByChinese** [comment]
You can subscribe to events on any `$scope` that descends from `$rootScope` (which in normal uses is the case). You can place breakpoints in those handlers, record information, emit console information, etc., or program specific application logic to respond to those events (such as show a dialog warning).

    $scope.$on('IdleStart', function() {
        // the user appears to have gone idle
    });

    $scope.$on('IdleWarn', function(e, countdown) {
        // follows after the IdleStart event, but includes a countdown until the user is considered timed out
        // the countdown arg is the number of seconds remaining until then.
        // you can change the title or display a warning dialog from here.
        // you can let them resume their session by calling Idle.watch()
    });

    $scope.$on('IdleTimeout', function() {
        // the user has timed out (meaning idleDuration + timeout has passed without any activity)
        // this is where you'd log them
    });

    $scope.$on('IdleEnd', function() {
        // the user has come back from AFK and is doing stuff. if you are warning them, you can use this to hide the dialog
    });

`IdleEnd` is the event that is broadcast when the user switches from idle back to not idle. Currently, I don't supply any information about the interrupting event (like a click or scroll) that caused the idle state to be reset. If that's useful, I can look into supplying that as a second parameter to that event.
