### ISSUE TITLE
Safari is not timing out when idle

### ISSUE THREAD

**Issue by gindulis** [HackedByChinese/ng-idle#160]
I have an issue with safari (OS X) not timing out as it should. I have created a simple example to demonstrate the issue here: https://output.jsbin.com/yohawi

It is set to show a warning message after user is idle for 10 seconds and afterwards there are 2 minutes timeout before user is 'redirected'.

**To reproduce the issue:** do not do anything or simply put the safari window in a background and use another application in the meantime.
Note: If user is interacting in safari developer tools, moving mouse and interacting with safari (nothing to trigger interrupt keydown mousedown touchstart in this case) timeout is working as expected.

**Expected:** user is redirected after 2 minutes pass.

**Actual:** user timeouts inconsistently 3-4 minutes and longer.

Found a similar issue commented on stackoverflow, but it is on mobile and was never solved: http://stackoverflow.com/questions/19168330/auto-logout-with-angularjs-based-on-idle-user#comment33727652_21457752

Do you have any idea how can I solve this?

**Comment by rkunboxed** [comment]
I can confirm the problem. It looks like any idle or timeout values over 60 seconds start going wonky in Safari.

**Comment by gindulis** [comment]
I have managed to fix the issue. The culprit was $interval service on Angular (1.3 in my case, [see here for more information](http://stackoverflow.com/questions/27557620/angular-1-3-interval-stops-executing-when-browser-is-minimized)). I have forked the repository and simply switched from $interval to $timeout with some minor changes to the code I got it working as expected.

**Comment by HackedByChinese** [comment]
The problem with using $timeout is that it will cause problems with Protractor tests. See #13. I'll see what's wrong with this as it exists in Safari.

**Comment by RacerDelux** [comment]
@HackedByChinese Any update on this?

**Comment by RacerDelux** [comment]
@HackedByChinese Pending close? #13 is closed.
