### ISSUE TITLE
ng-idle when closing browser / browser tab 

### ISSUE THREAD

**Issue by mshref17** [HackedByChinese/ng-idle#161]
When the user closes the browser/ browser tab of my applcation, and then open it again, ng-idle do not deal with user as idle user.... how to deal with this please

**Comment by HackedByChinese** [comment]
Ah... well in the meantime when your app initializes, you could clear out the contents of session storage. I'll look into patching the module to do that automatically.

**Comment by HackedByChinese** [comment]
Sorry, I amended my previous response. The module uses session storage, meaning when the app is closed and reopened, the session storage is effectively cleared and they are starting from scratch again.

It's best if you do session checking on your side first (usually this is done server side) to ensure someone is logged in. NgIdle should not be used in place of security/session checking, but rather to augment it and respond to user interaction on the client side.
