### ISSUE TITLE
Inject Dependencies in Module.config

### ISSUE THREAD

**Issue by Partho-paul** [HackedByChinese/ng-idle#164]
http://stackoverflow.com/questions/38488255/how-to-inject-module-config-dependencies-from-scope

**Comment by HackedByChinese** [comment]
You can use the following methods on `Idle` and `Keepalive` if you need to change the values post-config:

 - `Idle.setIdle()` to change the idle duration.
 - `Idle.setTimeout()` to change the timeout duration.
 - `Keepalive.setInterval()` to change the ping inverval.

Remember to call `Idle.watch()` after changing the values.

If you need to do any reconfig when the scope values change, just `$watch` them:

    function resetIdle() {
      Idle.setIdle($scope.IDLE_TIME);
      Idle.setTimeout($scope.TIMEDOUT_TIME);
      Idle.watch();
    }

    $scope.$watch('IDLE_TIME', resetIdle);
    $scope.$watch('TIMEDOUT_TIME', resetIdle);
    $scope.$watch('KEEPALIVE_TIME', function() {
       Keepalive.setInterval($scope.KEEPALIVE_TIME);
       Keepalive.start();
    });
