### ISSUE TITLE
How to configure which DOM events to watch? 

### ISSUE THREAD

**Issue by iavasquez** [HackedByChinese/ng-idle#166]
The wiki mentions that the DOM events that the idle provider will watch are configurable.  Can you add some info on what the options are and how to configure the idle provider to add or subtract DOM events to watch? 

_> **DOM Events**
> 
> The events Idle watches are configurable. It is important to note that if the watched user events are prevented from bubbling up, Idle will not be reset and thus not work properly. Usually this is not a problem._

**Comment by anuja-joshi** [comment]
@iavasquez  DOM events to be watched, can be configured using `interrupt` method.  Like if you want to watch only `mousedown` event then configure as follows: 
```
    IdleProvider.interrupt('mousedown');
```
for multiple events, event names are separated by space. Ex:
```
   IdleProvider.interrupt('mousedown keydown');
```
This method is from V1.0 , before that you have to use `activeOn` method. [here]( https://github.com/HackedByChinese/ng-idle/wiki/Idle-and-Idleprovider#idleprovider)  is link to wiki.

Hope this helps.
