### ISSUE TITLE
Change idle duration at runtime

### ISSUE THREAD

**Issue by nikakhov** [HackedByChinese/ng-idle#17]
How can I change idleDuration at runtime in a controller?

I can inject the $idle service like so:
.controller('EventsCtrl', function($scope, $idle)
Unforunately $idle does not have a property for changing the idleDuration.

**Comment by sheetalkanade** [comment]
For my app, I have a requirement to make session timeout configurable per user and this information is fetched from the server after login. So I want to update the idle duration through a service / controller after user session is established. I am using ngIdle but have hardcoded the value in config. Can I change it in the controller?

**Comment by sheetalkanade** [comment]
Never mind. I was using an older version of  ngIdle. Thank.

**Comment by atljoseph** [comment]
When you guys get solutions, please post them here for everyone else
