### ISSUE TITLE
re-direction on idleTimeout is not happening in all opened tabs

### ISSUE THREAD

**Issue by gitfortee** [HackedByChinese/ng-idle#175]
I have opened few tabs and when they are idle, a dialog pops up and if i continue to be idle, the timeout happens. All these work just fine. however, the timeout happening in one tab redirects the user to the login screen in that particular tab alone and all other tabs are not redirected. Further worse, for those tabs which did not redirect (this is becasue of the url. if it is the login screen, i am restricting the ng-idle events not to timeout or in other words to keep on watching) , the idle watch is restarted and does its job - which is meaning less at this point. 

Is there a way to handle tha above mentioned scenario..??

**Comment by HackedByChinese** [comment]
It's hard to say with the information provided. Your application should be set up to globally subscribe to the timeout event and redirect to your login page. If you are subscribing to the event only on certain controllers, then when those controllers go out of scope, they'll no longer be able to respond to the event.

You can manage this global handling a number of ways. One way is to simply set it up in your app's `.run` function:

```
angular.module('myApp', ['ngIdle'])
    .run([$rootScope, Idle, function($rootScope, Idle) {
         $rootScope.$on('IdleTimeout', function() {
             // redirect to login page
         });

         Idle.start();
     }]);
```

You could also place all this wireup in a service that you initialize during `run`.
