### ISSUE TITLE
Interrupt configuration is not working

### ISSUE THREAD

**Issue by rajarajac** [HackedByChinese/ng-idle#187]
Hi Team,

I am trying to configure the interrupt configuration on mousedown and keydown but it is not working.
Though the user is active in the application still idle popup is showing after 30 secs.
Please guide me, if i miss any?

 angular.module('SampleApp').config(['IdleProvider','KeepaliveProvider', function idleConfig(IdleProvider,KeepaliveProvider) {
        IdleProvider.idle(30);
        IdleProvider.timeout(30);
        IdleProvider.interrupt('keydown mousedown');
        IdleProvider.autoResume('off');
        IdleProvider.keepalive(false);
    }]);

**Comment by grbsk** [comment]
You have `autoResume('off')`, which means that interrupts won't ever reset the idle state. Maybe you meant [`autoResume('notIdle')`](https://github.com/HackedByChinese/ng-idle/wiki/Idle-and-Idleprovider)?
