### ISSUE TITLE
Dynamic timeout ?

### ISSUE THREAD

**Issue by v0d1ch** [HackedByChinese/ng-idle#189]
Is there a way to have dynamic timeout setting ? Scenario is that I have a service that fetches the timeout from backend and I want to be able to set it but I can not inject that fetcher service in config phase of the app and Idle.setTimeout(x) in run phase does not actually set my timeout properly. If I have hardcoded values like in the base example everything of course works but I think that dynamic setting would be a nice feature

**Comment by grbsk** [comment]
Have you called `watch()` after changing the timeout? setTimeout does not do that automatically.

**Comment by v0d1ch** [comment]
Right, working now as expected. Thanks!
