### ISSUE TITLE
cannot call $scope.stop from modal

### ISSUE THREAD

**Issue by sriramkondeti** [HackedByChinese/ng-idle#192]
Hi There, 

Could any one please let me know how to call $scope.stop function from a button click placed inside a modal window. Apparently am using the same template (warning-dialog.html) as per the intro page and have added two buttons "Continue", "Logout". 

"Continue" will close the modal and reset the timer - which is working fine.

but "Logout" button is unable to trigger $scope.stop(); - the expected functionality is to stop the timer and route to login page.As per my findings  $scope.$on('IdleEnd') is always triggered instead of stop function.

Could you please tell me if theres any work around to make the logout button call the stop function instead of triggering the idleEnd state.

<img width="360" alt="screen shot 2017-04-06 at 12 02 05 am" src="https://cloud.githubusercontent.com/assets/5425141/24714878/576c4b78-1a5c-11e7-8acb-e3a7102b6951.png">

Thanks a ton. Much appreciable if you can help

**Comment by grbsk** [comment]
You probably have autoresume set to true or similar. This means that any user activity will automatically reset their state (meaning, basically, that simply moving the mouse or similar is the same as clicking "continue" on your dialog). If you do not want this functionality, you can set `IdleProvider.autoResume('notIdle')`. This will let user activity interrupt their idle state _except_ if they go idle. This means they'll _have_ to click "continue" (which should call `idle.watch()`) if they want to stay logged in. "Log out" can simply perform your app's log out functionality.
