### ISSUE TITLE
Idle call is not getting triggered for Mobile App

### ISSUE THREAD

**Issue by rohanpractice** [HackedByChinese/ng-idle#198]
I have been using ng-idle for some time now. It is working properly for mobile browser but when I have implemented the same for IOS and Android App idle call is not getting triggered.

Same is getting triggered when i am doing inspect element.

**Comment by niczak** [comment]
I am in the same boat, is this plug-in supposed to work on mobile (Cordova) or not?

**Comment by grbsk** [comment]
I have no experience with Cordova, so I'm unable to provide direct support for it at this time.

**Comment by niczak** [comment]
@HackedByChinese Thanks for the reply! Turned out to be an unrelated issue which is now resolved.

I can say for certain that your plugin works great w/ Cordova!

**Comment by grbsk** [comment]
Thanks for letting us know!
