### ISSUE TITLE
IdleTimeout logic works only once

### ISSUE THREAD

**Issue by alexandroscgb** [HackedByChinese/ng-idle#199]
Hi.

I have an Angular app which does a logout action after 5 of inactivity, just for test, but after the first time, I login again, and the `$scope.$on('IdleTimeout', function() {        
        console.log("logging out");
        $scope.closeSession();
     });` fragment won't work again.

Any ideas?

Thanks.

**Comment by grbsk** [comment]
Sorry if this seems rather rudimentary, but let's try all the easy stuff first. Do you call `Idle.watch()` again after they have been logged back in?

**Comment by alexandroscgb** [comment]
Oh, man, of course, that is just right. Solved. Thanks so much.

**Comment by grbsk** [comment]
Glad it's solved!
