### ISSUE TITLE
Set idle and timeout time dynamically in angularjs

### ISSUE THREAD

**Issue by chetanganguly** [HackedByChinese/ng-idle#206]
Hey guys..I want to set idel and timeout ..time dynamically
myApp.config(['KeepaliveProvider', 'IdleProvider', function(KeepaliveProvider, IdleProvider) {
IdleProvider.idle(5);
IdleProvider.timeout(5);
KeepaliveProvider.interval(10);
}]);
Time in seconds come from db as client required
Using web API
How can I perform that?
Any idea please share

**Comment by grbsk** [comment]
At any time (post `config`) you can call [`Idle.setTimeout()` or `Idle.setIdle()`](https://github.com/HackedByChinese/ng-idle/wiki/Idle-and-Idleprovider#idle) to change those values.

**Comment by chetanganguly** [comment]
Thanks it worked
