### ISSUE TITLE
Karma/Jasmine tests failing due to ngIdle

### ISSUE THREAD

**Issue by yashdoshi89** [HackedByChinese/ng-idle#21]
```
Error: [$injector:modulerr] Failed to instantiate module ngIdle due to:
Error: [$injector:nomod] Module 'ngIdle' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

I have included ngIdle in karma.conf.js in this order

files: [
            'app/bower_components/angular/angular.js',
            'app/bower_components/angular-route/angular-route.js',
            'app/bower_components/angular-touch/angular-touch.js',
            'app/bower_components/angular-animate/angular-animate.js',
            'app/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js',
            'app/bower_components/angular-mocks/angular-mocks.js',
            'app/bower_components/angular-resource/angular-resource.js',
            'app/bower_components/revolunet-angular-carousel/lib/angular-mobile.js',
            'app/bower_components/revolunet-angular-carousel/src/angular-carousel.js',
            'app/bower_components/jquery/dist/jquery.js',
            'app/bower_components/angular-cookies/angular-cookies.min.js',
            'app/bower_components/ng-idle/angular-idle.min.js',
            'app/bower_components/ng-grid/ng-grid-2.0.11.min.js',
            'app/js/**/*.js',
            'test/spec/**/*.js'

What is it that I am missing? Because all my other libraries are working correctly. If I remove ngIdle code then my karma/jasmine tests are passing but with this all of my 100+ testcases are failing and giving the above error.

**Comment by vasanthakumarmk** [comment]
I too facing exact similar issue, could you please explain how did you resolved this issue?

**Comment by vasanthakumarmk** [comment]
> Hi Thanks for your help. It was something related to how our application was built. It's solved now. Really amazing ngIdle module.

It would be more greatful If you explain more about how did you resolved this issue.
