### ISSUE TITLE
Object doesn't support this property or method in IE8

### ISSUE THREAD

**Issue by guaravs900** [HackedByChinese/ng-idle#40]
Hi Mike,
I am using ng-idle with angular js version 1.2.16 in my application. It works fine on FireFox ,crome and Internet Explorer 9 ,10. But on window 7 Internet explorer 8. I am getting this error "Object doesn't support this property or method", does ng-Idle works on IE8 browser if yes can you please help me to resolve this issue.

Thanks,
Gaurav

**Comment by HackedByChinese** [comment]
I have not done any testing with IE 8. 

I'm of the opinion that a browser as old and crappy as IE 8 should die a horrible death, but I know what it's like to be stuck having to deal with it despite that opinion. 

Can you provide more details about the error (line numbers, etc.)? Perhaps it's a simple fix (like I used a reserved keyword when using a promise or something like that). We can try to get it working but I can't make any guarantees. =

**Comment by guaravs900** [comment]
Hey Mike,
Thanks for quick reply i have attached screen snap please have a look. If it is possible can you also try on your end or give me your skype id.  I have all the setup with IE8 browser

![capture](https://cloud.githubusercontent.com/assets/6145958/5649019/f52b5aae-96b8-11e4-83d7-f4482369fa11.PNG)

**Comment by jnelson** [comment]
Please see http://caniuse.com/#feat=queryselector. The footnote for IE8 is a basic explanation for the workarounds provided in https://code.angularjs.org/1.2.16/docs/guide/ie. In short, if you want IE8 support, you will need to help IE8 "understand" the typical way Angular HTML is written.
