### ISSUE TITLE
$idleProvider.autoResume(false)

### ISSUE THREAD

**Issue by xxJimxx** [HackedByChinese/ng-idle#47]
My anticipation of setting autoResume to false and my desired effect would be to autoResume except when in a warn state.  This would allow me to force the user to click a button to resume  the application from the warn state and restart the $idle.watch(). I do not want to always prompt after the idleDuration expires nor do I want autoResume once warning has started. Perhaps I'm asking for an additional feature.  

I do appreciate the work you have done and I would prefer to use your module without customizing your code.  Hopefully I have not become a pest.  Thanks,

**Comment by HackedByChinese** [comment]
autoResume was originally conceived only to cover whether or not the idle state could be reset automatically by user activity once they have gone idle.

I could make an amendment to autoResume where a value of `true`/`false` works as it has previously (for legacy purposes), but let it also take a string value that allows for advanced behaviors:

- `off`: do not auto resume ever (equivalent to `false` of today).
- `idle`: allow resuming if they are idle but not yet timed out (except when they have timed out, equivalent to `true` of today).
- `notIdle`: allow resuming so long as they have not yet gone idle.

**Comment by xxJimxx** [comment]
That sounds great, thank you.
