### ISSUE TITLE
Where is version 1.0.0?

### ISSUE THREAD

**Issue by janega** [HackedByChinese/ng-idle#50]
First I would like to say very nice work on this module!!! I love it so far and it is going to save me a lot of time. However, the latest release published is 0.3.5 in the release tab on GitHub, but also via installation with bower. I am confused because you have migration steps to use to get to version 1.0.0 in the Wiki, but I made the changes thinking I had version 1.0.0 but I did not. Why have migration steps for an unreleased version, I am missing something here?

**Comment by HackedByChinese** [comment]
I started documenting 1.0.0 changes as I was completing items so I didn't forget when it was released, but I have two issues left in the 1.0.0 milestone. I will hopefully have them done this week/early next week. 

Thanks,
Mike Grabski

**Comment by janega** [comment]
Awesome Thanks and Great work BTW!!!
