### ISSUE TITLE
Title isn't restored after idle ends

### ISSUE THREAD

**Issue by taybin** [HackedByChinese/ng-idle#52]
IdleEnd isn't broadcast anywhere, so the window title is never restored.

**Comment by HackedByChinese** [comment]
Can you provide a sample or point me to where I can take a look? I don't see any problem on my end. IdleEnd is called when you interrupt, aka someone moves the mouse or types, etc. _before IdleTimeout occurs_. If IdleTimeout occurs, the module will not automatically reset (it _will_ automatically reset if the user is _idling_, but not if they time out). Once they time out, the only way you can get them going again is to call `Idle.watch()` at your discretion.

Normally, when timeout happens, you're redirecting them to a login page or something.

**Comment by taybin** [comment]
This is on the develop branch. I grepped through the code and didn't see a broadcast or emit of IdleEnd anywhere.  What else would trigger the restoration of the original window title?

**Comment by HackedByChinese** [comment]
Lines 65-67 on idle.js is where it performs the broadcast.

The title directive only sets it back on IdleEnd event, whether you trigger the event yourself or `Idle` does it. You can also manually interact with the `Title` service to work with the title.

**Comment by taybin** [comment]
Hmm, okay.  I see.  This is probably invalid then.
I'm having trouble because I'm trying to bubble up events from within an iframe.  So I'm catching those events and calling Idle.interrupt().  However, if the idle dialog comes up and then goes away, the window title isn't restored.  Do you think I need to be calling Title.restore() on every event too?  It looks like Idle.interrupt() should be enough.

**Comment by taybin** [comment]
That was all a red herring.  The problem was that our title text was inside <title><span>foo</span></title>, so ng-idle thought there wasn't a title at all.

Having tags within <title> seems to be undefined, so I'm going to close this as a user error.
