### ISSUE TITLE
Rename the title service directive

### ISSUE THREAD

**Issue by dhoomm** [HackedByChinese/ng-idle#54]
I was trying to disable the title service, but it wouldn't work even after adding `idle-disabled="true"`.
Later i found that i had a image `<img src="..." title="some title" />`, So the value `idle-disabled="true"` was being overwritten later in the document.
It would be preferable to use tag name like idle-title to prevent conflicts.

**Comment by HackedByChinese** [comment]
Ah, no I forgot to limit the `title` directive to elements only. It's a simple fix and will cause it to only work with `title` HTML nodes.
