### ISSUE TITLE
Events are posted outside digest loop

### ISSUE THREAD

**Issue by fracz** [HackedByChinese/ng-idle#56]
I want to update `countdown` variable on my scope (progressbar animation, like in the demo).

```js
$scope.$on('IdleWarn', function(e, countdown) {
  $scope.countdown = countdown;
});
```

However, the scope is not refreshed. I need to:

```js
$scope.$on('IdleWarn', function(e, countdown) {
  $scope.$apply(function() {
    $scope.countdown = countdown;
  });
});
```

in order to have scope refreshed properly. IMHO, events should be dispatched inside `$apply`.

Tested on current master.

**Comment by karthilxg** [comment]
I was getting the *$digets alrready in progress error*, while trying to display the count down timer. *Commenting out the $apply does the trick*.

```javascript
$scope.$on('IdleWarn', function(e, countdown) {
          // $scope.$apply(function() {
            $scope.value = countdown;
          // });
        });
```
Error Stack:
2015-03-19 17:39:57.726angular.js:10126 Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.2.28/$rootScope/inprog?p0=NaNigest
    at VALIDITY_STATE_PROPERTY (http://localhost:9000/bower_components/angular/angular.js:78:12)
    at beginPhase (http://localhost:9000/bower_components/angular/angular.js:13122:15)
    at Scope.$get.Scope.$apply (http://localhost:9000/bower_components/angular/angular.js:12908:11)
    at http://localhost:9000/bower_components/ng-idle/angular-idle.js:292:18
    at Scope.$get.Scope.$broadcast (http://localhost:9000/bower_components/angular/angular.js:13093:28)
    at countdown (http://localhost:9000/bower_components/ng-idle/angular-idle.js:174:22)
    at Array.deferred.promise.then.wrappedProgressback (http://localhost:9000/bower_components/angular/angular.js:11700:88)
    at http://localhost:9000/bower_components/angular/angular.js:11668:28
    at Scope.$get.Scope.$eval (http://localhost:9000/bower_components/angular/angular.js:12811:28)
    at Scope.$get.Scope.$digest (http://localhost:9000/bower_components/angular/angular.js:12623:31)

**Comment by fracz** [comment]
You haven't read my issue carefully - changing scope insite event handling does not work without `$apply` call. This is also used in the [idle-countdown](https://github.com/HackedByChinese/ng-idle/blob/develop/src/countdown/countdown.js) directive.

Library should not force users to call `$apply` method. When target environment is not known (sometimes inside $digest loop, sometimes not), it may be good idea to implement sth like [safe `$apply`](https://coderwall.com/p/ngisma/safe-apply-in-angular-js).

It's not a big deal as one can cope with that easily. But I have spent some time investigating why my scope is not refreshed after receiving `IdleWarn` event.

**Comment by karthilxg** [comment]
@fracz Thanks !! Using safe apply resolves the issue.

**Comment by HackedByChinese** [comment]
When I originally laid out this module and looked at the right way to use `$broadcast` in a module, there was back-and-forth over whether or not broadcasting an event _should_ cause a digest (it does not), with plenty of reasonable arguments from either side. True enough, a number of `ng-idle` users raised concerns over issues where `ng-idle` causes digests (specifically that they don't want them).

In either case, it seems the most reasonable way to accommodate everyone is to err on the side of caution, but give people an easy-to-use alternative for those that don't want to apply (the `idle-countdown` directive).

Solutions to make this work are trivial, so I don't feel compelled to change it unless it seems everyone wants it. I should, however, at least make this issue and the way to resolve it much clearer in the wiki.
