### ISSUE TITLE
IE11 win7, over CPU usage

### ISSUE THREAD

**Issue by pranaydutta89** [HackedByChinese/ng-idle#59]
There is 100% cpu utilization in case of IE11 and win7 combination. On applying profilers i narrowed down and found that 

     var wrap = function(event) {
                     if (event.key === 'ngIdle.expiry') svc.interrupt();
                    };

this line is taking all the cpu 

this is happening when i upgraded to the latest version 1.0.0

**Comment by pranaydutta89** [comment]
its going on a infinite loop on that function

**Comment by rolandocc** [comment]
The same is happening with Windows 7 + IE 10. 
This event is supposed to be fired only when the user is active, however is infinite as @pranaydutta89  pointed out.

![image](https://cloud.githubusercontent.com/assets/1318512/6871353/92d2be3c-d467-11e4-8117-0bb9ff30ba29.png)

Everything works fine with Firefox and Chrome so this is probably an IE's issue only.

**Comment by HackedByChinese** [comment]
Once again, Microsoft can't read or plainly implement a [*&#$@%&ed spec](http://dev.w3.org/html5/webstorage/#the-localstorage-attribute). The `onstorage` event is not supposed to fire on the same window that caused the storage change, but they do, which is causing the infinite loop.

**Comment by rolandocc** [comment]
Thank you!

**Comment by pranaydutta89** [comment]
thanks a ton
