### ISSUE TITLE
Unknown Provider: $idleProvider with AngularJS 1.3.15

### ISSUE THREAD

**Issue by RevanProdigalKnight** [HackedByChinese/ng-idle#60]
![error](https://cloud.githubusercontent.com/assets/5728037/6897423/904f3e86-d6c1-11e4-98b2-990dad4c75f4.png)

Using version 1.0.2 of ng-idle

**Comment by HackedByChinese** [comment]
Please refer to the 1.0.0 migration guide. https://github.com/HackedByChinese/ng-idle/wiki/Migrating-to-version-1.0.0-from-0.x

**Comment by RevanProdigalKnight** [comment]
It might be helpful to move that towards the top (maybe under the requirements) in your description, I just saw that now.

**Comment by HackedByChinese** [comment]
In addition to the README, it's also in the Release Notes (Github UI) and wik.
