### ISSUE TITLE
Configure timeouts after the configuration phase

### ISSUE THREAD

**Issue by ertanden** [HackedByChinese/ng-idle#63]
My application has a backend where I store the idle timeout values and I retrieve those values with a RESTFul interface, which needs authentication, so not possible in configuration phase.

Is there a way to set the timeout values in a controller, instead of config function?

Maybe "Idle.watch()" can be updated to support getting timeout values as parameters. That would be really nice.

**Comment by HackedByChinese** [comment]
The `idle` and `timeout` values can now be set at any time after configuration. See [`Idle` wiki entry](https://github.com/HackedByChinese/ng-idle/wiki/Idle-and-Idleprovider#idle)

**Comment by ertanden** [comment]
I just saw the Wiki. Thanks. Great work.
