### ISSUE TITLE
Get current timeout values that are set in Idle service

### ISSUE THREAD

**Issue by ertanden** [HackedByChinese/ng-idle#64]
It would be nice to be able to access current timeout values with methods like;

Idle.getIdle()
Idle.getTimeout()

I saw there's a _options method which returns the options object, but I guess it's not meant to be used externally or am I wrong?

**Comment by JCherryhomes** [comment]
put in a pull request for this enhancement, let me know if I need to change anything. Included a couple simple tests in the idle.spec file as well
