### ISSUE TITLE
High CPU utilization under IE

### ISSUE THREAD

**Issue by tsonev** [HackedByChinese/ng-idle#68]
Hi,
I just noticed that under Windows 7 - IE 10.0.9200 there is a very high (~40% while window is focused) CPU utilization while ng-idle is writing to the localStorage.

Profiler under IE pins it down to line 407:

storage.setItem('ngIdle.'+key, JSON.stringify(value));

What is the need for ng-idle to : 
1.User localStorage at all to record the last used date
2.Write on such short intervals(tens of times per sec) to the localStorage.

**Comment by sw-web** [comment]
Latest version uses an angular method instead of JSON.stringify. It probably won't change anything and this doesn't answer your questions, but it's worth a try

**Comment by HackedByChinese** [comment]
What version are you using? A fix was put out in v1.0.2 for IE. IE is erroneously calling onstorage in the same window that changed a value causing a feedback loop. 

I'll check again but in my tests with IE after the changes it was fixed.

**Comment by tsonev** [comment]
Im using 1.0.1. WIll try out 1.0.2 now.

**Comment by tsonev** [comment]
Its the same with 1.0.4
![ie_profiler](https://cloud.githubusercontent.com/assets/5079047/7068456/325f48e4-dedb-11e4-8e68-cb125865864c.png)

**Comment by tsonev** [comment]
OK I tried using sessionStorage instead and it looks much better, but still 3-4 % of the CPU is busy.
Had it integrated with https://github.com/jmdobry/angular-cache and did some tests. It works best with storageMode:'none' -- which would put the value in the browser memory. However Im not sure how this will be handled on mobile devices.

			angular.module('ngIdle.localStorage', ['jmdobry.angular-cache'])
			  .service('iolCacheServiceLocal', ['$angularCacheFactory', function ($angularCacheFactory) {
						var myCache = $angularCacheFactory('iolCache', {
							maxAge: 3600000 * 24, // Items added to this cache expire after 1 day
							cacheFlushInterval: 3600000 * 24, // This cache will clear itself every day.
							deleteOnExpire: 'aggressive', // Items will be deleted from this cache right when they expire.
							storageMode: 'localStorage'
						});
			return myCache;
		}])
	.service('iolCacheServiceSess', ['$angularCacheFactory', function ($angularCacheFactory) {
			var myCache = $angularCacheFactory('iolCacheSession', {
				maxAge: 3600000 * 24, // Items added to this cache expire after 1 day
				cacheFlushInterval: 3600000 * 24, // This cache will clear itself every day.
				deleteOnExpire: 'aggressive', // Items will be deleted from this cache right when they expire.
				storageMode: 'sessionStorage'
			});


			return myCache;
		}])
	.service('iolCacheServiceMemory', ['$angularCacheFactory', function ($angularCacheFactory) {
		var myCache = $angularCacheFactory('iolCacheMemory', {
			maxAge: 3600000 * 24, // Items added to this cache expire after 1 day
			cacheFlushInterval: 3600000 * 24, // This cache will clear itself every day.
			deleteOnExpire: 'aggressive', // Items will be deleted from this cache right when they expire.
			storageMode: 'none'
		});

		return myCache;
	}])
			  .service('IdleLocalStorage', ['iolCacheServiceMemory', function(iolCacheService) {
            var storage = iolCacheService;

            return {
                set: function(key, value) {
                    storage.put('ngIdle.'+key, angular.toJson(value));
                },
                get: function(key) {
                    return angular.fromJson(storage.get('ngIdle.'+key));
                },
                remove: function(key) {
                    storage.remove('ngIdle.'+key);
                }
            };
        }]);

**Comment by mithun-daa** [comment]
1.0.4 fixed my issue - IE was getting non-responsive while setting up some timers. The new version fixed it for me. Thanks.
