### ISSUE TITLE
Publish to NPM registry

### ISSUE THREAD

**Issue by sw-web** [HackedByChinese/ng-idle#69]
To be able to use this package seamlessly with node, it should be published to the NPM registry. This push can be done automatically by travis, or manually from cli.

Let me know if you want me to handle this (I guess I will still need you to provide me with the api key, I have no exp on this topic...)

**Comment by HackedByChinese** [comment]
1.0.4 is published. I'll look into automatic publishing of tagged releases in the future. Thanks.
