### ISSUE TITLE
Warning countdown is interrupted and idle state is reset without user activity in IE11

### ISSUE THREAD

**Issue by pdrosos** [HackedByChinese/ng-idle#74]
Hello,

I have an issue with IE11 on Windows 7, which can also be seen on the plugin demo page http://hackedbychinese.github.io/ng-idle/

When I click the Start demo button and stop moving the mouse the warning countdown pop-up shows up and disappears alone after 2-3 seconds, without any user activity or moving the mouse. And the idle state is reset. This happens only if the mouse is inside the page body. If the mouse is outside the page, for example over the browser address bar or the menu bar, the demo works normally, the warning countdown pop-up does not disappear and the timeout pop-up is shown after that.

I have tried the same on a colleague's computer with IE11 and Windows 7, where the demo works normally as expected. So I am not completely sure if it's a bug, or the bug was fixed with some Windows update and will appreciate any feedback.

My IE11 version, where the problem exists is 11.0.9600.17633. My colleague's IE11 version, where the problem can not be reproduced is 11.0.9600.17728.

Thank you in advance for your help!

**Comment by xxJimxx** [comment]
Reviewing for update from pre 1.0 and needed to test this.  I am using IE ver 11.0.9600.17843 and did not encounter this issue on the demo page.
