### ISSUE TITLE
Idle Service getExpiry() Function Throwing an Error on Empty Local Storage

### ISSUE THREAD

**Issue by dustymiller** [HackedByChinese/ng-idle#76]
The getExpiry() function (line 199) throws an 'error getting property time of undefined' when LocalStorage.get does not find an object named 'expiry' in storage.  Should perhaps check for existence of returned object before trying to access its 'time' property?

This occurs because I empty out local storage as part of my application cleanup, and somewhere along the line getExpiry is being called after my cleanup has occurred.  Should I call Idle.unwatch() before I initiate my cleanup?

**Comment by HackedByChinese** [comment]
Calling unwatch should get you around it for now, but I suppose getExpiry should be more resilient.
