### ISSUE TITLE
How to stop listening to all mouse movement and random click but continue to countdown idle

### ISSUE THREAD

**Issue by herious1989** [HackedByChinese/ng-idle#80]
Hi,

This is a scenario I encounter:
- When the dialog pops up during IdleWarn, all mouse movements resume the timeout which goes against the purpose of asking user to click Resume button to clear the timeout.
- Question is how can I while showing to dialog, keep the timeout continue to run unless a specific button is pressed.

THanks

**Comment by joero4** [comment]
Funny you should as for this.  I needed to do the same thing, so I forked the project and added the functionality.  I have it working in my app now.  If you want you can try my fork at https://github.com/joero4/ng-idle.  I will do a pull request as well if the author is interested in bringing in this functionality.  

To use my solution you can do something like...

```javascript
$scope.$on('IdleStart', function () {
        Idle.uninterrupt();
        App.Dialog.show({
            content: 'Please be warned that you will be automatically logged out in 5 minutes due to inactivity.  Click the Ok button to keep your session active.',
            actions: [],
            height: '130px',
            buttons: [
                {
                    text: 'Ok',
                    click: function () {
                        Idle.interrupt();
                        App.Dialog.close();
                    }
                }
            ]
        });
    });
```

Be aware of the use of Idle.uninterrupt() and Idle.interrupt().

I hope this helps.

**Comment by HackedByChinese** [comment]
The `autoResume` option `notIdle` should cover this scenario. Under this scenario, DOM events will keep the timeout from occurring, but once the user goes idle, further DOM events will not automatically reset the timeout (meaning you'll need to call `Idle.watch()` yourself to resume their session, which is what you're asking for).

Setting this up goes like this:

.config(function(IdleProvider) {
   IdleProvider.autoResume('notIdle');
  // the rest of your configuration
})

This was added in v1.0.0. See the [wiki](https://github.com/HackedByChinese/ng-idle/wiki/Idle-and-Idleprovider#idleprovider) for more information.
