### ISSUE TITLE
ngIdle does not work when system in sleep

### ISSUE THREAD

**Issue by yashikagarg13** [HackedByChinese/ng-idle#83]
If user logs in to the application, put the system on sleep and when he return to application after the  idle time (say 30 mins), the session didn't expire ever.

**Comment by Sayene** [comment]
@yashikagarg13  you can use 'Keepalive' event to to store 'lastTimestamp" and compare with current time. Calculating the difference, you can detect if system was asleep (JS interrupted) and call your logout/session expired actions.

**Comment by HackedByChinese** [comment]
recent versions of ng-idle handle this, however people have noted some issues concerning localStorage and some browser artifacts. I'll close this as a general issue that has been addressed, if you have a specific problem using this feature either contribute your observations to a similar ticket or create a new one if you feel it's a new issue.
