### ISSUE TITLE
When using autoResume('notIdle'), 'IdleEnd' is not being broadcast

### ISSUE THREAD

**Issue by joero4** [HackedByChinese/ng-idle#84]
I am currently at the end of a release, so I'm sorry I could not do more testing with this, but maybe you can tell me what I'm doing wrong.  I'm trying to use the autoResume('notIdle') feature so that the user must click on a button before it interrupts.  the issue I'm seeing is that the 'IdleEnd' event is not being broadcast when I click my button, and therefore other "Idle windows" are being closed.  Here is what I have...

```javascript
sessionApp.config(['KeepaliveProvider', 'IdleProvider', function (KeepaliveProvider, IdleProvider) {
    IdleProvider.idle(TIMEOUT_WARNING_AFTER*60);
    IdleProvider.timeout(TIMEOUT_AFTER * 60);
    IdleProvider.autoResume('notIdle');
}]).run(['$rootScope', '$rootElement', '$timeout', 'Idle', 'Keepalive', function ($rootScope, $rootElement, $timeout, Idle, Keepalive) {


    $rootScope.$on('IdleStart', function () {
        App.Dialog.show({
            content: 'Please be warned that you will be automatically logged out in ' + Math.round(Idle.getTimeout() / 60) + ' minutes due to inactivity.  Click the Ok button to keep your session active.',
            actions: [],
            height: '130px',
            buttons: [
                {
                    text: 'Ok',
                    click: function () {
                        Idle.interrupt();
                        //Idle.watch();
                        App.Dialog.close();
                    }
                }
            ]
        });
    });

    $rootScope.$on('IdleEnd', function() {
        Idle.interrupt();
        App.Dialog.close();
    });

    Idle.watch();
}]);
```

**Comment by HackedByChinese** [comment]
A few things:

1. I would use `watch()`, not `interrupt()` (see the [wiki](https://github.com/HackedByChinese/ng-idle/wiki/Idle-and-Idleprovider#interrupt-vs-watch) for more info).
2. Calling either during `IdleEnd` is superfluous.
3. I suppose my assumption is that if you're manually resetting the idle state, firing the event is superfluous because it's telling you that something happened which you already know happened.

**Comment by HackedByChinese** [comment]
I'm doing some housecleaning. If you don't feel my answer addresses your needs, reopen with more details as to why.
