### ISSUE TITLE
Using multiple instances of this?

### ISSUE THREAD

**Issue by rondog** [HackedByChinese/ng-idle#85]
Not really an issue, but more of a question. I am currently using this to log a user out if they are idle for 8 minutes.

I have a video player that has some video controls I'd like to hide when the mouse is idle. I could do this fine, if I wasn't already using this module for idle logout. Is it possible to have two instances of this?

**Comment by HackedByChinese** [comment]
No, it's not possible to have multiple instances. It's also probably a bit overkill for just hiding elements when a mouse is not moving or hovering over the element.
