### ISSUE TITLE
Security error if cookies disabled

### ISSUE THREAD

**Issue by crawlem** [HackedByChinese/ng-idle#86]
Disabling cookies in Firefox leads to the following error: "SecurityError: The operation is insecure".

**Comment by HackedByChinese** [comment]
The multitab/window feature uses localStorage to manage expiration between instances. There is currently no way to disable this, so I've recorded a request @ #91 to disable this feature. It's all or nothing, though; You can't have localStorage with cookies disabled, so your choices are to either require cookies or turn off the multitab/window feature.
