### ISSUE TITLE
How to avoid title changing.

### ISSUE THREAD

**Issue by d4n13l3** [HackedByChinese/ng-idle#87]
Hello,
is there a config parameter to set to avoid page title change?

I'm using this for a project but i had to edit the ```state``` object like this:

```
var state = {
      original: '',
      idle: '',
      timedout: ''
    };
```

Thanks!

**Comment by HackedByChinese** [comment]
You can add `idle-disabled="true"` to your title to opt-out of automatic title changes. See the [wiki](https://github.com/HackedByChinese/ng-idle/wiki/Title#usage).

**Comment by d4n13l3** [comment]
Thanks a lot, I missed that!
Il 27/mag/2015 21:17, "Mike Grabski" <notifications@github.com> ha scritto:
