### ISSUE TITLE
Setup timeout at IdleStart event causing IdleWarn not appearing

### ISSUE THREAD

**Issue by kwangsa** [HackedByChinese/ng-idle#98]
I created plunkr http://plnkr.co/edit/0mkNfee9DotCfqPJdgzp?p=preview to show if 

Idle.setTimeout() happen when IdleStart event happen all other event is not broadcasted.

**Comment by HackedByChinese** [comment]
I'm not sure what you're trying to accomplish. `setTimeout` is used in the event that your application or users want to change the timeout value once the application is already running. When it is called, it starts the watch all over again, effectively resetting the idle/timeout state.

I don't know why you are calling it within the IdleStart event, but at any rate it won't work.
